version: '3.9'

services:
  backend:
    # Removed: image: ghcr.io/blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
    # Removed: pull_policy: always
    # Force build from local source with Azore customizations
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 8.1.1
        DISABLE_WEBAPP: "false"
        ADMIN_PANEL_ENABLED: "true"
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    # network_mode: "host"  # Uncomment this line if using local database
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    environment:
      - DISABLE_WEBAPP=false
      - ADMIN_PANEL_ENABLED=true
    ports:
      - "5000:5000"
    volumes:
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/
